### ISSUE TITLE
Design Community Stats Page

### ISSUE THREAD

**Issue by fzyang1227** [Code-4-Community/speak-for-the-trees-frontend#238]
**Why**
- To show statistics about AAT program contributions.
- Show the contributions of users by neighborhood for tree adoptions and stewardship

**What to do**
- Design the page for community stats according to our design consistency
- Include filters for time period/neighborhood for both adoption and stewardship activities

> refer to 2.2.5
https://docs.google.com/document/d/15xKMNdEydFd6dM-wd1_lRwTFrN2Zk0pwMY0bXZqlUCo/edit?usp=sharing

**Comment by huang0h** [comment]
Closing as the page is no longer needed
