### ISSUE TITLE
Design User Stats Page

### ISSUE THREAD

**Issue by fzyang1227** [Code-4-Community/speak-for-the-trees-frontend#239]
**Why**
- allows the user to see aggregate statistics about their contributions

**What to do**
- design the page around the following:
    - user's name and contributions
    - how many trees the user adopted + which ones
    - how many stewardship activities done for each tree and in total for a specific timeframe

> refer to 2.2.6
https://docs.google.com/document/d/15xKMNdEydFd6dM-wd1_lRwTFrN2Zk0pwMY0bXZqlUCo/edit?usp=sharing

**Comment by huang0h** [comment]
Closing as the page is no longer needed
