### ISSUE TITLE
Update My Trees Page

### ISSUE THREAD

**Issue by fzyang1227** [Code-4-Community/speak-for-the-trees-frontend#240]
**Why**
- add in new features to the my trees page

**What to do**
- implement the tree images, environmental benefits, layouts etc.
- follow the below design spec:
> https://www.figma.com/proto/Rj1fh2FeRNrJlcVq161xcc/SFTT-2022-2023?page-id=206%3A410&node-id=416-812&viewport=-467%2C-1564%2C0.2&scaling=scale-down&starting-point-node-id=414%3A459&show-proto-sidebar=1

**Comment by chromium-52** [comment]
Todo:
* About this tree and additional information now take on new formatting.
* The image should be displayed as shown on the prototype.
* Only users who have adopted the tree and admins can modify/upload tree photos.
* Users uploaded tree photos will have the option to remain anonymous (this can be done with a checkbox that is by default checked).
